### DISCUSSION TITLE
DatetimePicker not picking up theme text color in dark mode

### DISCUSSION THREAD

**Discussion by opticSquid** [ng-matero/extensions#321] [Q&A] [answered]
I am using datetime picker with material UI 3.
When I'm using the component the output looks like this:
![20240625_103246.jpg](https://github.com/ng-matero/extensions/assets/59192460/6c404f53-1d75-4627-bb24-298e0c83df42)

With very much difficulty you can see the calendar.

The HTML code looks like this:
![20240625_102257.jpg](https://github.com/ng-matero/extensions/assets/59192460/b919cf96-f77f-4bf8-8458-c5d69aa48f60)

In the root stylesheet (styles.scss) I have:
![20240625_102529.jpg](https://github.com/ng-matero/extensions/assets/59192460/923b7849-a524-4ec6-afdc-d53c04f871ae)

I'm asking here with lot of hope to help me fix this. Please help me out I have a release on this Friday.

**Comment by opticSquid** [comment]
> I am using datetime picker with material UI 3.
> When I'm using the component the output looks like this:
> ![20240625_103246.jpg](https://github.com/ng-matero/extensions/assets/59192460/6c404f53-1d75-4627-bb24-298e0c83df42)
> 
> With very much difficulty you can see the calendar.
> 
> The HTML code looks like this:
> ![20240625_102257.jpg](https://github.com/ng-matero/extensions/assets/59192460/b919cf96-f77f-4bf8-8458-c5d69aa48f60)
> 
> In the root stylesheet (styles.scss) I have:
> ![20240625_102529.jpg](https://github.com/ng-matero/extensions/assets/59192460/923b7849-a524-4ec6-afdc-d53c04f871ae)
> 
> I'm asking here with lot of hope to help me fix this. Please help me out I have a release on this Friday.
> 

@nzbin please help if you can

**Reply by opticSquid** [reply]
If you need more details please let me know.

**Comment by nzbin** [comment, marked as answer]
👇  **Very important**
```scss
$light-theme: mat.private-deep-merge-all( 
  mat.define-theme($light-config), 
  mtx.define-theme($light-config) 
); 
```

https://github.com/ng-matero/extensions/blob/43fae8e7ab11f09f18a73c0ab3ff8ce05e79d78f/projects/docs/src/styles.scss#L10-L27

**Reply by opticSquid** [reply]
ok let me try this once

**Reply by opticSquid** [reply]
yes this works many thanks @nzbin. 😊

**Comment by liemwellys** [comment]
![image](https://github.com/ng-matero/extensions/assets/11076479/fbab52ab-a998-4064-a79b-104a7a4752c4)

Hi, I think I'm facing the same problem like as mentioned above. The datetime picker becomes transparent.

Currently I'm implementing datetime picker on angular 14 project & using angular material 14. I have imported `MtxDatetimepickerModule` & `MtxNativeDatetimeModule` into needed module. My current code for implementing this feature is as follows:

```html
<mat-form-field
  class="form"
  appearance="outline"
  *ngIf="selectedTimeFilter(i) !== 'between'"
>
  <mat-label>{{ t('filterMenu.selectDateTime') }}</mat-label>
  <input
    matInput
    [mtxDatetimepicker]="picker_i"
    placeholder="{{ t('filterMenu.selectDateTime') }}"
    [formControlName]="'dateTime'"
  />
  <mtx-datetimepicker
    #picker_i
    [type]="'datetime'"
    [mode]="'auto'"
    [multiYearSelector]="false"
    [startView]="'month'"
    [twelvehour]="false"
    [touchUi]="false"
    [timeInput]="true"
  ></mtx-datetimepicker>
  <mtx-datetimepicker-toggle
    [for]="$any(picker_i)"
    matSuffix
  ></mtx-datetimepicker-toggle>
</mat-form-field>
```
Is there any solution for this issue? Thanks in advance.

**Reply by liemwellys** [reply]
Based on the previous answer by @nzbin, I finally found the solution by add the following config into `styles.scss` file and now it works perfectly.

```scss
@use "@angular/material" as mat;
@use "@ng-matero/extensions" as mtx;

// Define custom color palettes
$primary-palette: mat.define-palette(mat.$indigo-palette);
$accent-palette: mat.define-palette(mat.$pink-palette, A200, A100, A400);
$warn-palette: mat.define-palette(mat.$red-palette);

// Define the default (light) theme using the custom palettes
$light-theme: mat.define-light-theme((
  color: (
    primary: $primary-palette,
    accent: $accent-palette,
    warn: $warn-palette,
  )
));

// Include the default theme styles for Angular Material components and extensions
:root {
  @include mat.all-component-themes($light-theme);
  @include mtx.all-component-themes($light-theme);
}
```
result:
![image](https://github.com/ng-matero/extensions/assets/11076479/661eecf0-4dff-41c2-9419-95b7260df05d)
