### ISSUE TITLE
mtx-select: Custom optgroup template has unnecessary extra height spacing

### ISSUE THREAD

**Issue by AlonsoK28** [ng-matero/extensions#174]
Lastest v15 add extra height spacing for "group title dropdown" template and the v14 does not seem to have it

```scss
.ng-dropdown-panel .ng-dropdown-panel-items .ng-optgroup {
    height: 3em; // this seem to be the issue
    padding: 14px 16px;
    font-weight: 500;
    -webkit-user-select: none;
    user-select: none;
    cursor: pointer;
}
```

- project documentation issue example https://ng-matero.github.io/extensions/components/select/overview#custom-optgroup-template
<img width="951" alt="Captura de pantalla 2023-01-16 a la(s) 14 44 09" src="https://user-images.githubusercontent.com/37458700/212763342-a453258f-4662-4e9c-a4d8-06c2f960b8c0.png">

- my own project with the issue on v15
<img width="496" alt="Captura de pantalla 2023-01-16 a la(s) 14 50 47" src="https://user-images.githubusercontent.com/37458700/212763743-e3580adb-4067-497e-9ddd-280d8b983111.png">

- my own project without the issue on v14
<img width="496" alt="Captura de pantalla 2023-01-16 a la(s) 14 51 20" src="https://user-images.githubusercontent.com/37458700/212763802-4acbb79f-8add-4931-a3d0-8725d5728731.png">

- my environment config
```js
"dependencies": {
 "@ng-matero/extensions": "^15.0.1",
 "@angular/core": "^15.1.0"
}
```
