### ISSUE TITLE
How to wrap long text in mtx-option?

### ISSUE THREAD

**Issue by casingwire** [ng-matero/extensions#202]
Hello, kindly help me figure out how to adjust the style to wrap a long text in an option value. It works with native mat-select using the css: 

.mat-select-panel mat-option.mat-option {
    height: unset;
    margin: 10px;
  }

.mat-option-text.mat-option-text {
    white-space: normal;
  }

I will very much appreciate it.

**Comment by nzbin** [comment]
```css
.ng-dropdown-panel .ng-dropdown-panel-items .ng-option {
  white-space: normal !important;
}
```
