### ISSUE TITLE
Configure z-index on loader

### ISSUE THREAD

**Issue by GianlucaLocri** [ng-matero/extensions#339]
Hi, new extension user here! First of all a big THANKS for this amazing work!

I'm using the loader component to wrap an angular material table like this 

```
<mtx-loader loading="true" type="spinner" color="primary" hasBackdrop="true">
  <table mat-table [dataSource]="data">
    // omissis
  </table>
</mtx-loader>
```

however the result is somewhat broken. The table is covered by backdrop except for the header that is visible.
I digged a bit and I found that material table uses z-index = 100 for the header.

I tried to modify my component css to include this
```
.mtx-loader-backdrop {
    z-index: 200;
}

.mtx-loader-main {
    z-index: 300;
}
```
but the code is obviously not working due to view encapsulation...

Can you suggest the proper way to do this?
Thanks!

**Comment by nzbin** [comment]
```scss
:host ::ng-deep {
  .mtx-loader-backdrop {
      z-index: 200;
  }
  
  .mtx-loader-main {
      z-index: 300;
  }
}
```
