### ISSUE TITLE
[GRID] Is it possible to put the progress bar between toolbar and header.

### ISSUE THREAD

**Issue by JDurand35** [ng-matero/extensions#385]
Hello, 

When I use the loader with the toolbar, the loader is above the toolbar. Is it possible to move it between the toolbar and the header?

Thanks

**Comment by nzbin** [comment]
Just modify the CSS
```css
mtx-grid .mtx-grid-progress {
  top: 60px;
}
```
