### ISSUE TITLE
Drawers theming overrides

### ISSUE THREAD

**Issue by AlonsoK28** [ng-matero/extensions#410]
Its possible to use overrides to modify [drawer](https://ng-matero.github.io/extensions/components/drawer/api) background color?

example:

``` ts
@use '@angular/material' as mat;

// Customize the entire app. Change :root to your selector if you want to scope the styles.
:root {
  @include mat.dialog-overrides((
    container-color: orange,
    subhead-color: red,
  ));
}
```

**Comment by nzbin** [comment]
![Image](https://github.com/user-attachments/assets/a6cb15d2-c1d2-417e-85b3-a24b3b78c6ea)

**Comment by AlonsoK28** [comment]
in my case this is my theme config

``` scss
//theme.drawer.scss
@use '@angular/material' as mat;

@mixin my-drawer-theme($theme) {
  $neutral-color-low: mat.get-theme-color($theme, neutral, 12);

  .mtx-drawer-container {
    background-color: $neutral-color-low;
  }
}
```
