### ISSUE TITLE
Header Text Truncation with Ellipsis When Resizing

### ISSUE THREAD

**Issue by UseMuse** [ng-matero/extensions#419]
#### **Problem:**

I am using a resizable column header, but I need the text in the header to **truncate with an ellipsis (`...`)** when the column is resized to its minimum width and the text no longer fits.

### **Expected Behavior:**

1. The column header should be resizable.
2. When the column width reaches the minimum and the text no longer fits, the text should **truncate with an ellipsis (`...`)**.

### **Current Behavior:**

Currently, when resizing the column to its minimum width, the text in the header does not truncate with an ellipsis. Instead, it either overflows or is fully visible.

### **Steps to Reproduce:**

1. Create a resizable column 
2. Add a text in the column header.
3. Resize the column to its minimum width and observe the text truncation behavior.

### **What I've Tried:**

* Applied `text-overflow: ellipsis`, `white-space: nowrap`, and `overflow: hidden` to the text, but it doesn't work when the column reaches the minimum width.

### **Questions:**

* How can I ensure that the **text in the column header truncates with an ellipsis** when the column is resized to its minimum width?

**Comment by UseMuse** [comment]
https://ng-matero.github.io/extensions/components/grid/overview#column-resize

as an example, change the Mobile column size to minimum, I would like to have ellipsis when the text does not fit in the width

**Comment by nzbin** [comment]
```scss
.mtx-grid .mat-header-cell-inner,
.mtx-grid .mat-sort-header,
.mtx-grid .mat-sort-header-content {
  width: 100%;
}

.mat-sort-header-content span {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
