### ISSUE TITLE
mtx-grid [columnResizable] not working as expected using v19+

### ISSUE THREAD

**Issue by gonzda** [ng-matero/extensions#428]
This stackblitz [https://stackblitz.com/edit/stackblitz-starters-2vhwenqy?file=package.json](url) is fine using "@ng-matero/extensions" v18, but if you change the dependency  to v19 or higher and then reinstall it ("npm install"), it no longer allows the user to resize the columns.

**Comment by nzbin** [comment]
The v19+ uses m3 theme and it doesn't export resize styles. You should customize the theme with sass.

```scss
@use '@angular/material' as mat;
@use '@ng-matero/extensions' as mtx;

html {
  color-scheme: light;

  @include mat.theme(
    (
      color: (
        primary: mat.$azure-palette,
        tertiary: mat.$blue-palette,
      ),
      typography: Roboto,
      density: 0,
    )
  );
}
```
